-- Tue Jan 18 11:35:50 2022
-- generated by svn post-commit hook (by atronah)
START TRANSACTION;
INSERT INTO `DatabaseUpdateInfo` 
(`id`, `revision`, `user`, `execDatetime`, `updateDate`, `issueNumber`, `note`, `completed`, `updateNumber`) 
VALUES 
(NULL, 48474, CURRENT_USER, CURRENT_TIMESTAMP, '2022-01-18', '', '', 0, '2022-007');

INSERT INTO rbuserRight (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, code, name) VALUES
('0000-00-00 00:00:00', NULL, '0000-00-00 00:00:00', NULL, 'viewInformationOnAllSites', 'Право на просмотр информации по всем учатскам');

-- generated by svn post-commit hook (by atronah)
UPDATE `DatabaseUpdateInfo`
	SET completed = 1 
WHERE 
	`revision` = 48474 AND `updateDate` = '2022-01-18' AND `issueNumber` = '';
COMMIT;