-- Thu Jan 27 09:39:19 2022
-- generated by svn post-commit hook (by atronah)
START TRANSACTION;
INSERT INTO `DatabaseUpdateInfo` 
(`id`, `revision`, `user`, `execDatetime`, `updateDate`, `issueNumber`, `note`, `completed`, `updateNumber`) 
VALUES 
(NULL, 48606, CURRENT_USER, CURRENT_TIMESTAMP, '2022-01-27', '', '', 0, '2022-022');

-- nameTail: export_files_M_and_E
-- DEV_VM-3396: Изменения в счетах на 2022 год (Положение 26)
-- КРАСНОДАРСКИЙ КРАЙ!!!
-- ФАЙЛЫ M и E

-- WEI IN FILE_P
ALTER TABLE `ExportFileP`
ADD COLUMN IF NOT EXISTS `WEI` DECIMAL(4, 1) DEFAULT NULL COMMENT 'Масса тела (кг)' AFTER `DATR`;
ALTER TABLE `tempFileP`
ADD COLUMN IF NOT EXISTS `WEI` DECIMAL(4, 1) DEFAULT NULL COMMENT 'Масса тела (кг)' AFTER `DATR`;

-- ENP IN FILE_P
ALTER TABLE `ExportFileP`
ADD COLUMN IF NOT EXISTS `ENP` VARCHAR(16) DEFAULT NULL COMMENT 'Единый номер полиса ОМС' AFTER `SPN`;
ALTER TABLE `tempFileP`
ADD COLUMN IF NOT EXISTS `ENP` VARCHAR(16) DEFAULT NULL COMMENT 'Единый номер полиса ОМС' AFTER `SPN`;

-- COMENTSL IN FILE_P
ALTER TABLE `ExportFileP`
ADD COLUMN IF NOT EXISTS `COMENTSL` VARCHAR(250) DEFAULT NULL COMMENT 'Служебное поле' AFTER `FKEY`;
ALTER TABLE `tempFileP`
ADD COLUMN IF NOT EXISTS `COMENTSL` VARCHAR(250) DEFAULT NULL COMMENT 'Служебное поле' AFTER `FKEY`;

-- COMENTSL IN FILE_U
ALTER TABLE `ExportFileU`
ADD COLUMN IF NOT EXISTS `COMENTSL` VARCHAR(250) DEFAULT NULL COMMENT 'Служебное поле' AFTER `RKEY`;
ALTER TABLE `tempFileU`
ADD COLUMN IF NOT EXISTS `COMENTSL` VARCHAR(250) DEFAULT NULL COMMENT 'Служебное поле' AFTER `RKEY`;

-- ExportFileM
DROP TABLE IF EXISTS ExportFileM;
CREATE TABLE IF NOT EXISTS ExportFileM (
    id INT(11) NOT NULL AUTO_INCREMENT,
    accountItem_id INT(11) NOT NULL COMMENT 'Идентификатор позиции счета',
    MID INT(14) DEFAULT NULL,
    CODE_MO VARCHAR(5) DEFAULT NULL,
    NS DECIMAL(5, 0) DEFAULT NULL,
    SN DECIMAL(12, 0) DEFAULT NULL,
    UID INT(14) DEFAULT NULL,
    DATE_MED DATE DEFAULT NULL,
    CODE_MDV DECIMAL(14, 0) DEFAULT NULL,
    NUMBER_SER VARCHAR(100) DEFAULT NULL,
    RKEY VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX IDX_accountItem (accountItem_id),
    CONSTRAINT AI_ExportFileM FOREIGN KEY (accountItem_id) REFERENCES Account_Item (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Таблица для файла выгрузки `M` (КК)';

-- tempFileM
DROP TABLE IF EXISTS tempFileM;
CREATE TABLE IF NOT EXISTS tempFileM (
  id             INT(11) NOT NULL AUTO_INCREMENT,
  accountItem_id INT(11) DEFAULT NULL COMMENT 'Идентификатор позиции счета',
  MID            INT(14) DEFAULT NULL,
  CODE_MO        VARCHAR(5) DEFAULT NULL,
  NS             DECIMAL(5, 0) DEFAULT NULL,
  SN             DECIMAL(12, 0) DEFAULT NULL,
  UID            INT(14) DEFAULT NULL,
  DATE_MED       DATE DEFAULT NULL,
  CODE_MDV       DECIMAL(14, 0) DEFAULT NULL,
  NUMBER_SER     VARCHAR(100) DEFAULT NULL,
  RKEY           VARCHAR(50) DEFAULT NULL,
  status         TINYINT     NOT NULL DEFAULT 0 COMMENT 'Статус импорта',
  importDateTime DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата импорта',
  number         INTEGER(11) NOT NULL DEFAULT 0 COMMENT 'Номер импорта',
  PRIMARY KEY (`id`),
  KEY `ix_UID`(`UID`),
  KEY `ix_number_status`(`number`, `status`),
  KEY `ix_datetime`(`importDateTime`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='Таблица для импорта файла выгрузки `M` (КК)';

-- ExportFileE
DROP TABLE IF EXISTS ExportFileE;
CREATE TABLE IF NOT EXISTS ExportFileE (
    id INT(11) NOT NULL AUTO_INCREMENT,
    accountItem_id INT(11) NOT NULL COMMENT 'Идентификатор позиции счета',
    EID INT(14) DEFAULT NULL,
    CODE_MO VARCHAR(5) DEFAULT NULL,
    NS DECIMAL(5, 0) DEFAULT NULL,
    SN DECIMAL(12, 0) DEFAULT NULL,
    UID INT(14) DEFAULT NULL,
    DATA_INJ DATE DEFAULT NULL,
    CODE_SH VARCHAR(10) DEFAULT NULL,
    REGNUM VARCHAR(6) DEFAULT NULL,
    COD_MARK VARCHAR(100) DEFAULT NULL,
    ED_IZM VARCHAR(3) DEFAULT NULL,
    DOSE_INJ DECIMAL(5, 2) DEFAULT NULL,
    METHOD_INJ VARCHAR(3) DEFAULT NULL,
    COL_INJ DECIMAL(14, 0) DEFAULT NULL,
    RKEY VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX IDX_accountItem (accountItem_id),
    CONSTRAINT AI_ExportFileE FOREIGN KEY (accountItem_id) REFERENCES Account_Item (id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Таблица для файла выгрузки `E` (КК)';

-- tempFileE
DROP TABLE IF EXISTS tempFileE;
CREATE TABLE IF NOT EXISTS tempFileE (
  id             INT(11) NOT NULL AUTO_INCREMENT,
  accountItem_id INT(11) DEFAULT NULL COMMENT 'Идентификатор позиции счета',
  EID            INT(14) DEFAULT NULL,
  CODE_MO        VARCHAR(5) DEFAULT NULL,
  NS             DECIMAL(5, 0) DEFAULT NULL,
  SN             DECIMAL(12, 0) DEFAULT NULL,
  UID            INT(14) DEFAULT NULL,
  DATA_INJ       DATE DEFAULT NULL,
  CODE_SH        VARCHAR(10) DEFAULT NULL,
  REGNUM         VARCHAR(6) DEFAULT NULL,
  COD_MARK       VARCHAR(100) DEFAULT NULL,
  ED_IZM         VARCHAR(3) DEFAULT NULL,
  DOSE_INJ       DECIMAL(5, 2) DEFAULT NULL,
  METHOD_INJ     VARCHAR(3) DEFAULT NULL,
  COL_INJ        DECIMAL(14, 0) DEFAULT NULL,
  RKEY           VARCHAR(50) DEFAULT NULL,
  status         TINYINT     NOT NULL DEFAULT 0 COMMENT 'Статус импорта',
  importDateTime DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата импорта',
  number         INTEGER(11) NOT NULL DEFAULT 0 COMMENT 'Номер импорта',
  PRIMARY KEY (`id`),
  KEY `ix_UID`(`UID`),
  KEY `ix_number_status`(`number`, `status`),
  KEY `ix_datetime`(`importDateTime`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='Таблица для импорта файла выгрузки `E` (КК)';


-- generated by svn post-commit hook (by atronah)
UPDATE `DatabaseUpdateInfo`
	SET completed = 1 
WHERE 
	`revision` = 48606 AND `updateDate` = '2022-01-27' AND `issueNumber` = '';
COMMIT;