-- Mon Feb  7 10:57:11 2022
-- generated by svn post-commit hook (by atronah)
START TRANSACTION;
INSERT INTO `DatabaseUpdateInfo` 
(`id`, `revision`, `user`, `execDatetime`, `updateDate`, `issueNumber`, `note`, `completed`, `updateNumber`) 
VALUES 
(NULL, 48723, CURRENT_USER, CURRENT_TIMESTAMP, '2022-02-07', '', '', 0, '2022-025');

-- nameTail: add_ENP
-- DEV_VM-3107: add ENP identifier

INSERT INTO rbAccountingSystem (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, code, name,
                                    isEditable, showInClientInfo, isUnique, counter_id, autoIdentificator)
VALUES (now(), null, now(), null, 'ENP', 'Единый номер полиса', 0, 1, 1, null, 0);

-- generated by svn post-commit hook (by atronah)
UPDATE `DatabaseUpdateInfo`
	SET completed = 1 
WHERE 
	`revision` = 48723 AND `updateDate` = '2022-02-07' AND `issueNumber` = '';
COMMIT;