-- Fri Nov 26 18:40:31 2021
-- generated by svn post-commit hook (by atronah)
START TRANSACTION;
INSERT INTO `DatabaseUpdateInfo` 
(`id`, `revision`, `user`, `execDatetime`, `updateDate`, `issueNumber`, `note`, `completed`, `updateNumber`) 
VALUES 
(NULL, 47999, CURRENT_USER, CURRENT_TIMESTAMP, '2021-11-26', '', '', 0, '2021-174');

-- nameTail: add_vac_properties
-- DEV_VM-3203: Добавление "Вакцинации" в учет рабочего времени
-- Новые типы пропертей для резервирования номерков через сервис записи на вакцинацию

create table rbinfection_code
(
    id                int auto_increment
        primary key,
    code              varchar(8)   not null comment 'Код',
    shortname         varchar(64)  not null comment 'Наименование',
    name              varchar(128) not null comment 'Наименование для отображения'
)
    comment 'Код инфекции';

INSERT INTO
  ActionPropertyType (actionType_id, name, shortName, descr, typeName, valueDomain, norm, sex, age, isVector, defaultValue)
VALUES
  ((SELECT id FROM ActionType WHERE name like '%Прием%' and code like '%amb%' and deleted = 0 LIMIT 0, 1), 'vac1', '', '', 'Reference', 'rbinfection_code', '', 0, '', 0, ''),
  ((SELECT id FROM ActionType WHERE name like '%Прием%' and code like '%amb%' and deleted = 0 LIMIT 0, 1), 'vac2', '', '', 'Reference', 'rbinfection_code', '', 0, '', 0, ''),
  ((SELECT id FROM ActionType WHERE name like '%Прием%' and code like '%amb%' and deleted = 0 LIMIT 0, 1), 'vacs', '', '', 'Reference', 'rbinfection_code', '', 0, '', 1, '');

-- generated by svn post-commit hook (by atronah)
UPDATE `DatabaseUpdateInfo`
	SET completed = 1 
WHERE 
	`revision` = 47999 AND `updateDate` = '2021-11-26' AND `issueNumber` = '';
COMMIT;