select *
from ActionType where class = 0 and name regexp 'женская';


select * from ActionType where group_id = 85258;


drop temporary table temp_at;
create temporary table temp_at
    (
        select 'Выписка из медицинской карты амбулаторного больного' as name union
        select 'Исход переменности' as name
    );


select NOW()                                                                         createDatetime,
       null                                                                          createPerson_id,
       NOW()                                                                         modifyDatetime,
       NULL                                                                          modifyPerson_id,
       0                                                                             deleted,
       class,
       group_id,
       concat('122_', (select count(id) + 1 from ActionType where group_id = 85258)) code,
       temp_at.name as                                                               name,
       title,
       needReferral,
       flatCode,
       sex,
       age,
       office,
       showInForm,
       genTimetable,
       quotaType_id,
       concat('122_', (select count(id) + 1 from ActionType where group_id = 85258)) context,
       amount,
       amountEvaluation,
       defaultStatus,
       defaultDirectionDate,
       defaultPlannedEndDate,
       defaultEndDate,
       defaultExecPerson_id,
       defaultSetPerson_id,
       defaultPersonInEvent,
       defaultPersonInEditor,
       defaultMKB,
       defaultMorphology,
       isMorphologyRequired,
       defaultOrg_id,
       maxOccursInEvent,
       isMES,
       nomenclativeService_id,
       showTime,
       isPreferable,
       prescribedType_id,
       shedule_id,
       isRequiredCoordination,
       isNomenclatureExpense,
       hasAssistant,
       propertyAssignedVisible,
       propertyUnitVisible,
       propertyNormVisible,
       propertyEvaluationVisible,
       serviceType,
       actualAppointmentDuration,
       visible,
       isSubstituteEndDateToEvent,
       isPrinted,
       withoutAgree,
       defaultMES,
       frequencyCount,
       frequencyPeriod,
       frequencyPeriodType,
       isStrictFrequency,
       isFrequencyPeriodByCalendar,
       counter_id,
       period,
       singleInPeriod,
       checkPeriod,
       isCustomSum,
       recommendationExpirePeriod,
       recommendationControl,
       lis_code,
       isExecRequiredForEventExec,
       isActiveGroup,
       locked,
       filledLock,
       refferalType_id,
       defaultBeginDate,
       showAPOrg,
       filterPosts,
       filterSpecialities,
       isIgnoreEventExecDate,
       advancePaymentRequired,
       checkPersonSet,
       defaultIsUrgent,
       checkEnterNote,
       EGISZ_code,
       EGISZ_typecons_code,
       SMS,
       SEMD,
       consultationTypeId,
       formulaAlias,
       instrumentalId,
       old_group_id,
       old_id,
       code_f30,
       code_f14
from ActionType,
     temp_at
where id = (select id from ActionType where group_id = 85258 limit 1);