insert into Person(createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, deleted, code, federalCode, regionalCode, lastName, firstName, patrName, post_id, speciality_id, org_id, orgStructure_id, office, office2, tariffCategory_id, finance_id, retireDate, ambPlan, ambPlan2, ambNorm, homPlan, homPlan2, homNorm, expPlan, expNorm, login, password, userProfile_id, retired, birthDate, birthPlace, sex, SNILS, INN, availableForExternal, lastAccessibleTimelineDate, timelineAccessibleDays, canSeeDays, academicDegree, typeTimeLinePerson, addComment, commentText, maritalStatus, contactNumber, regType, regBegDate, regEndDate, isReservist, employmentType, occupationType, citizenship_id, isDefaultInHB, isInvestigator, syncGUID, qaLevel, signature_cert, signature_key, ecp_password, grkmGUID, token, disableSignDoc, mse_speciality_id, llo_login, llo_password, llo_code, isVk, doctorRoomAccessDenied, consultDepartment_id, email, cashier_code)
select *
from (select
             now() createDatetime,
             null createPerson_id,
             now() modifyDatetime,
             null modifyPerson_id,
             deleted,
             s.code,
             federalCode,
             s.code regionalCode,
             s.lastName,
             s.firstName,
             s.patrName,
             null post_id,
             null speciality_id,
             null org_id,
             null orgStructure_id,
             '' office,
             office2,
             tariffCategory_id,
             finance_id,
             retireDate,
             ambPlan,
             ambPlan2,
             ambNorm,
             homPlan,
             homPlan2,
             homNorm,
             expPlan,
             expNorm,
             concat(s.lastName, left(s.patrName,1), left(s.firstName, 1)),
             password,
             null userProfile_id,
             retired,
             str_to_date(s.birthDate, '%d.%m.%Y') birthDate,
             birthPlace,
             sex,
             convert(regexp_replace(s.SNILS, '-|\\s', ''), char) SNILS,
             convert(s.INN, char) INN,
             availableForExternal,
             lastAccessibleTimelineDate,
             timelineAccessibleDays,
             canSeeDays,
             academicDegree,
             typeTimeLinePerson,
             addComment,
             commentText,
             maritalStatus,
             contactNumber,
             regType,
             str_to_date(s.regBegDate, '%d.%m.%Y') as regBegDate,
             regEndDate,
             isReservist,
             employmentType,
             occupationType,
             citizenship_id,
             isDefaultInHB,
             isInvestigator,
             syncGUID,
             qaLevel,
             signature_cert,
             signature_key,
             ecp_password,
             grkmGUID,
             token,
             disableSignDoc,
             mse_speciality_id,
             llo_login,
             llo_password,
             llo_code,
             isVk,
             doctorRoomAccessDenied,
             consultDepartment_id,
             email,
             cashier_code
      from Person p, `SUP-23821` s where p.id = (select id from Person where p.deleted = 0 order by id desc limit 1)) as tmp
where not exists(select *
                 from Person p
                 where tmp.lastName = p.lastName
                   and tmp.patrName = p.patrName
                   and tmp.firstName = p.firstName
                   and tmp.deleted = p.deleted
                   and tmp.birthDate = p.birthDate
                   and tmp.SNILS = p.SNILS
                   and tmp.INN = p.INN)