insert into actiontype (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, deleted, class, group_id, code, name, title, flatCode, sex, age, office, showInForm, genTimetable, quotaType_id, context, amount, amountEvaluation, defaultStatus, defaultDirectionDate, defaultPlannedEndDate, defaultEndDate, defaultExecPerson_id, defaultSetPerson_id, defaultPersonInEvent, defaultPersonInEditor, defaultMKB, defaultMorphology, isMorphologyRequired, defaultOrg_id, maxOccursInEvent, isMES, nomenclativeService_id, showTime, isPreferable, prescribedType_id, shedule_id, isRequiredCoordination, isNomenclatureExpense, generateStockMotionReason, hasAssistant, propertyAssignedVisible, propertyUnitVisible, propertyNormVisible, propertyEvaluationVisible, serviceType, actualAppointmentDuration, exposeDateSelector, ticketDuration, nomenclatureClass_id, nomenclatureKind_id, nomenclatureType_id, closeEvent, addVisit, addVisitScene_id, addVisitType_id, isSubstituteEndDateToEvent, isPrinted, defaultMES, frequencyCount, frequencyPeriod, frequencyPeriodType, isStrictFrequency, isFrequencyPeriodByCalendar, counter_id, isCustomSum, recommendationExpirePeriod, recommendationControl, isExecRequiredForEventExec, isActiveGroup, lis_code, locked, filledLock, refferalType_id, defaultBeginDate, showAPOrg, showAPNotes, filterPosts, filterSpecialities, isIgnoreEventExecDate, advancePaymentRequired, checkPersonSet, defaultIsUrgent, checkEnterNote, formulaAlias, eventStatusMod, isAllowedAfterDeath, isAllowedDateAfterDeath)
select 
now() createDatetime, null createPerson_id, now() modifyDatetime, null modifyPerson_id, 
a.deleted, a.class, a.group_id, '14693' code, 'Выписной эпикриз' name, a.title, a.flatCode, a.sex, a.age, a.office, a.showInForm, a.genTimetable, a.quotaType_id, a.context, a.amount, a.amountEvaluation, a.defaultStatus, a.defaultDirectionDate, a.defaultPlannedEndDate, a.defaultEndDate, a.defaultExecPerson_id, a.defaultSetPerson_id, a.defaultPersonInEvent, a.defaultPersonInEditor, a.defaultMKB, a.defaultMorphology, a.isMorphologyRequired, a.defaultOrg_id, a.maxOccursInEvent, a.isMES, a.nomenclativeService_id, a.showTime, a.isPreferable, a.prescribedType_id, a.shedule_id, a.isRequiredCoordination, a.isNomenclatureExpense, a.generateStockMotionReason, a.hasAssistant, a.propertyAssignedVisible, a.propertyUnitVisible, a.propertyNormVisible, a.propertyEvaluationVisible, a.serviceType, a.actualAppointmentDuration, a.exposeDateSelector, a.ticketDuration, a.nomenclatureClass_id, a.nomenclatureKind_id, a.nomenclatureType_id, a.closeEvent, a.addVisit, a.addVisitScene_id, a.addVisitType_id, a.isSubstituteEndDateToEvent, a.isPrinted, a.defaultMES, a.frequencyCount, a.frequencyPeriod, a.frequencyPeriodType, a.isStrictFrequency, a.isFrequencyPeriodByCalendar, a.counter_id, a.isCustomSum, a.recommendationExpirePeriod, a.recommendationControl, a.isExecRequiredForEventExec, a.isActiveGroup, a.lis_code, a.locked, a.filledLock, a.refferalType_id, a.defaultBeginDate, a.showAPOrg, a.showAPNotes, a.filterPosts, a.filterSpecialities, a.isIgnoreEventExecDate, a.advancePaymentRequired, a.checkPersonSet, a.defaultIsUrgent, a.checkEnterNote, a.formulaAlias, a.eventStatusMod, a.isAllowedAfterDeath, a.isAllowedDateAfterDeath from actiontype a where a.name regexp 'выписно' limit 1


select * from actiontype a where a.name = 'Выписной эпикриз';


select * from actionpropertytype a where a.actionType_id = 64469;