select apt.* from ActionType at2, ActionPropertyType apt 
where at2.group_id in (select at3.id from ActionType at3 where at3.code in('КТ - уКРТбк','КТ- уКРТом'))
and apt.actionType_id = at2.id


select * from rbJobType rjt ;





-- Thu Jul 13 13:30:05 2017
-- generated by svn post-commit hook (by atronah)
START TRANSACTION;
INSERT INTO DatabaseUpdateInfo
(`id`, `revision`, `user`, `execDatetime`, `updateDate`, `issueNumber`, `note`, `completed`, `updateNumber`) 
VALUES 
(NULL, 27549, CURRENT_USER, CURRENT_TIMESTAMP, '2017-07-13', '3791', 'Добавление поля для сохранения модификатора статуса работы', 0, '2017-076');

-- nameTail: add_jobStatusModifier_column
-- i3791. Добавление поля для сохранения модификатора статуса работы

ALTER TABLE rbJobType
  ADD COLUMN jobStatusModifier INTEGER NULL COMMENT 'Модификатор состояния работы (0 - не задано, 1 - выполняется, 2 - закончено)';


-- generated by svn post-commit hook (by atronah)
UPDATE `DatabaseUpdateInfo`
	SET completed = 1 
WHERE 
	`revision` = 27549 AND `updateDate` = '2017-07-13' AND `issueNumber` = '3791';
COMMIT;



select * from DatabaseUpdateInfo dui order by id DESC ;