insert into OrgStructure (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, deleted, organisation_id, code, name, parent_id, type, net_id, chief_id, headNurse_id, isArea, hasHospitalBeds, hasStocks, hasDayStationary, infisCode, infisInternalCode, infisDepTypeCode, availableForExternal, address, infisTariffCode, inheritEventTypes, inheritActionTypes, inheritGaps, bookkeeperCode, dayLimit, storageCode, salaryPercentage, attachCode, isVisibleInDR, tfomsCode, syncGUID, quota, miacCode, netrica_Code, idLPU_egisz, netrica_Code_UO, netrica_Code_IEMK, attachOperOrgStructure_id)
select
       now() createDatetime,
       NULL createPerson_id,
       now() modifyDatetime,
       NULL modifyPerson_id,
       deleted,
       organisation_id,
       code,
       'Рентген-урология 2-этаж' name,
       parent_id,
       type,
       net_id,
       chief_id,
       headNurse_id,
       isArea,
       hasHospitalBeds,
       hasStocks,
       hasDayStationary,
       infisCode,
       infisInternalCode,
       infisDepTypeCode,
       availableForExternal,
       address,
       infisTariffCode,
       inheritEventTypes,
       inheritActionTypes,
       inheritGaps,
       bookkeeperCode,
       dayLimit,
       storageCode,
       salaryPercentage,
       attachCode,
       isVisibleInDR,
       tfomsCode,
       syncGUID,
       quota,
       miacCode,
       netrica_Code,
       idLPU_egisz,
       netrica_Code_UO,
       netrica_Code_IEMK,
       attachOperOrgStructure_id
from OrgStructure where parent_id = 159 limit 1