
insert into rbPrintTemplate (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, code, name, context, fileName, `default`, dpdAgreement, type, banUnkeptDate, counter_id, deleted, isPatientAgreed, groupName, documentType_id, hideParam, isEditableInWeb, chkProfiles, chkPersons)
select *
from
(select
       now() as createDatetime,
       NULL as createPerson_id,
       now() as modifyDatetime,
       NULL modifyPerson_id,
       'SUP-20258' as code,
       'Протокол установления факта смерти человека' as name,
       'SUP-20258' as context,
       '' as fileName,
       '' as `default`,
       dpdAgreement,
       type,
       banUnkeptDate,
       counter_id,
       deleted,
       isPatientAgreed,
       groupName,
       documentType_id,
       hideParam,
       isEditableInWeb,
       chkProfiles,
       chkPersons
from rbPrintTemplate order by id desc limit 1 ) as tmp
where not exists(select * from rbPrintTemplate where name = tmp.name and code = tmp.code);


select *
from rbPrintTemplate where id = 654;

set @name = 'Протокол сердечно-лёгочной реанимации';
set @code = 'SUP-20258';

insert into ActionType (createDatetime, createPerson_id, modifyDatetime, modifyPerson_id, deleted, class, group_id, code, name, title, flatCode, sex, age, office, showInForm, genTimetable, quotaType_id, context, amount, amountEvaluation, defaultStatus, defaultDirectionDate, defaultPlannedEndDate, defaultEndDate, defaultExecPerson_id, defaultSetPerson_id, defaultPersonInEvent, defaultPersonInEditor, defaultMKB, defaultMorphology, isMorphologyRequired, defaultOrg_id, showTime, maxOccursInEvent, isMES, nomenclativeService_id, isPreferable, prescribedType_id, shedule_id, isRequiredCoordination, isNomenclatureExpense, hasAssistant, propertyAssignedVisible, propertyUnitVisible, propertyNormVisible, propertyEvaluationVisible, serviceType, actualAppointmentDuration, isSubstituteEndDateToEvent, isPrinted, defaultMES, frequencyCount, frequencyPeriod, frequencyPeriodType, isStrictFrequency, isFrequencyPeriodByCalendar, counter_id, isCustomSum, recommendationExpirePeriod, recommendationControl, isExecRequiredForEventExec, isActiveGroup, lis_code, locked, filledLock, defaultBeginDate, refferalType_id, filterPosts, filterSpecialities, isIgnoreEventExecDate, showAPOrg, showAPNotes, defaultIsUrgent, advancePaymentRequired, checkEnterNote, formulaAlias, isAllowedAfterDeath, isAllowedDateAfterDeath, eventStatusMod)
select *
from
(select
       NOW() createDatetime,
       NULL createPerson_id,
       now() modifyDatetime,
       NULL modifyPerson_id,
       deleted,
       class,
       group_id,
       @code as code,
       @name as name,
       'Протокол сердечно-лёгочной реанимации' as title,
       flatCode,
       sex,
       age,
       office,
       showInForm,
       genTimetable,
       quotaType_id,
       context,
       amount,
       amountEvaluation,
       defaultStatus,
       defaultDirectionDate,
       defaultPlannedEndDate,
       defaultEndDate,
       defaultExecPerson_id,
       defaultSetPerson_id,
       defaultPersonInEvent,
       defaultPersonInEditor,
       defaultMKB,
       defaultMorphology,
       isMorphologyRequired,
       defaultOrg_id,
       showTime,
       maxOccursInEvent,
       isMES,
       nomenclativeService_id,
       isPreferable,
       prescribedType_id,
       shedule_id,
       isRequiredCoordination,
       isNomenclatureExpense,
       hasAssistant,
       propertyAssignedVisible,
       propertyUnitVisible,
       propertyNormVisible,
       propertyEvaluationVisible,
       serviceType,
       actualAppointmentDuration,
       isSubstituteEndDateToEvent,
       isPrinted,
       defaultMES,
       frequencyCount,
       frequencyPeriod,
       frequencyPeriodType,
       isStrictFrequency,
       isFrequencyPeriodByCalendar,
       counter_id,
       isCustomSum,
       recommendationExpirePeriod,
       recommendationControl,
       isExecRequiredForEventExec,
       isActiveGroup,
       lis_code,
       locked,
       filledLock,
       defaultBeginDate,
       refferalType_id,
       filterPosts,
       filterSpecialities,
       isIgnoreEventExecDate,
       showAPOrg,
       showAPNotes,
       defaultIsUrgent,
       advancePaymentRequired,
       checkEnterNote,
       formulaAlias,
       isAllowedAfterDeath,
       isAllowedDateAfterDeath,
       eventStatusMod
from ActionType where group_id is null order by id desc limit 1) as tmp
where not exists(select * from ActionType where name = tmp.name and code = tmp.code);